server:
  port: 8887


spring:
  datasource:
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://172.17.199.37:3306/SpringBoot-JPA?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

    properties:
      hibernate:
        format_sql: true
